import { stripOwnedLines } from './frontmatter.mjs';

/**
 * Compare an adopted skill against its vendored baseline.
 *
 * SKILL.md is compared with the script-owned lines removed, so the `-copy`
 * rename and the internal flag never read as drift. Everything else is byte
 * comparison.
 */
export function diffSkill({ mine, base }) {
  const changed = [];
  for (const [path, content] of mine) {
    if (!base.has(path)) {
      changed.push({ path, kind: 'added' });
      continue;
    }
    const a = path.endsWith('SKILL.md') ? stripOwnedLines(content) : content;
    const b = path.endsWith('SKILL.md') ? stripOwnedLines(base.get(path)) : base.get(path);
    if (a !== b) changed.push({ path, kind: 'edited' });
  }
  for (const path of base.keys()) {
    if (!mine.has(path)) changed.push({ path, kind: 'removed' });
  }
  return { status: changed.length === 0 ? 'verbatim' : 'modified', changed };
}

const begin = (marker) => `<!-- ${marker}:begin -->`;
const end = (marker) => `<!-- ${marker}:end -->`;

/** Replace the body between two HTML comment markers, leaving the rest alone. */
export function replaceRegion(text, marker, body) {
  const open = text.indexOf(begin(marker));
  const close = text.indexOf(end(marker));
  if (open === -1 || close === -1 || close < open) {
    throw new Error(`document is missing the ${begin(marker)} / ${end(marker)} markers`);
  }
  const head = text.slice(0, open + begin(marker).length);
  const tail = text.slice(close);
  return `${head}\n${body}\n${tail}`;
}

const ORIGIN = (source) => (source === null || source === undefined ? 'own work' : source);

export function renderSkillTable(entries) {
  const folders = [...new Set(entries.map((e) => e.key.split('/')[0]))].sort();
  const out = [];
  for (const folder of folders) {
    out.push(`#### ${folder}`, '', '| Skill | Origin | State | Shipped |', '| --- | --- | --- | --- |');
    const rows = entries
      .filter((e) => e.key.startsWith(`${folder}/`))
      .sort((a, b) => a.name.localeCompare(b.name));
    for (const e of rows) {
      out.push(`| \`${e.name}\` | ${ORIGIN(e.source)} | ${e.status} | ${e.internal ? 'internal' : 'yes'} |`);
    }
    out.push('');
  }
  return out.join('\n').trimEnd();
}

export function renderNotices(provenance) {
  const { upstreams, skills } = provenance;
  const counts = new Map();
  for (const entry of Object.values(skills)) {
    if (!entry.source) continue;
    counts.set(entry.source, (counts.get(entry.source) ?? 0) + 1);
  }

  const out = [
    '# Third-party notices',
    '',
    'Generated by `node scripts/skills.mjs check`. Do not edit by hand.',
    '',
    'Skills adapted from the repositories below. Each upstream is mirrored verbatim on',
    'the `vendor` branch, alongside its own licence, at the commit recorded here.',
    '',
    '| Upstream | Repository | Pinned commit | Licence | Copyright | Skills adopted |',
    '| --- | --- | --- | --- | --- | --- |',
  ];

  for (const [name, u] of Object.entries(upstreams)) {
    const repo = u.path ? `${u.repo} (\`${u.path}/\`)` : u.repo;
    out.push(
      `| \`${name}\` | [${repo}](https://github.com/${u.repo}) | \`${u.sha}\` | ${u.license} | ${u.holder} | ${counts.get(name) ?? 0} |`
    );
  }

  out.push('', 'Full licence text for each upstream is at `vendor/<upstream>/LICENSE` on the `vendor` branch.', '');
  return out.join('\n');
}
